### ISSUE TITLE
Calculated sunrise is too early - Time Zone Problem?

### ISSUE THREAD

**Issue by MiWeiss** [udivankin/sunrise-sunset#4]
Possible duplicate of #2, but to be sure, I created a new issue. Also, this one might be a bit easier to reproduce.

**Setup:** 
We're checking the sunrise for Zermatt, Switzerland. Coordinates and Sunrise according to Google:
<img src="https://user-images.githubusercontent.com/4815944/56084742-be464800-5e37-11e9-8e52-7277e37c8b70.png" width="200"> <img src="https://user-images.githubusercontent.com/4815944/56084839-a7085a00-5e39-11e9-8115-116f1b155494.png" width="200">
(Source of both images: Google.com)

**Bug:**
![image](https://user-images.githubusercontent.com/4815944/56084783-999ea000-5e38-11e9-887a-8ca0ea8e6582.png)
The calculated time (04:47 CEST) is 2 hours off.

the same can be reproduced using the following command
`getSunrise(46.0207, 7.7491, new Date('Sat Apr 13 2019 21:51:00 GMT+0200 (Central European Summer Time)'));`

I suspect that the difference is caused by the time zone offset between CEST and UTC.

**Comment by udivankin** [comment]
Thanks for this request, I appreciate it!
Closing as fixed.
